[project]
name = "penguin-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pipreqs>=0.5.0",
    "scikit-learn>=1.8.0",
    "transformers>=4.57.3",
]
